spring:
  # 连接池配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/store_admin?useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#  profiles:
#    active: cache,mq
  thymeleaf:
    cache: true  #开启缓存
    check-template: true  #检查模板是否存在
    check-template-location: true # 检查模板位置正确性 默认查找 resources templates文件夹内
    servlet:
      content-type: text/html # 直接嵌入到html文件中
    enabled: true
    encoding: UTF-8

